<#
.SYNOPSIS
  Renders docs/response-curve.svg straight from BrightnessCore.ps1.

.DESCRIPTION
  The chart in the README is not a drawing of what the algorithm is supposed to do - it is
  generated by calling the algorithm. Every point on every curve is a real
  Get-TargetBrightness result for a real NOAA sun altitude, so the picture cannot drift
  away from the behaviour the way a hand-made diagram silently does.

  Regenerate after changing the model:

      pwsh -File .\Tools\New-CurveChart.ps1

.PARAMETER Latitude
  Degrees north. The default is a generic mid-latitude so the chart is not tied to
  whoever happens to have installed it.

.PARAMETER Date
  The day to plot. An equinox keeps day and night close to even, which shows the twilight
  ramp at its most legible.
#>
[CmdletBinding()]
param(
    [double]  $Latitude  = 50.0,
    [double]  $Longitude = 0.0,
    [datetime]$Date      = '2026-03-20',
    [string]  $OutPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path (Split-Path $PSScriptRoot -Parent) 'BrightnessCore.ps1')

if (-not $OutPath) {
    $OutPath = Join-Path (Split-Path $PSScriptRoot -Parent) 'docs/response-curve.svg'
}

# ---------------------------------------------------------------------------
# geometry
# ---------------------------------------------------------------------------
$W = 880.0; $H = 400.0
$L = 58.0; $R = 168.0; $T = 34.0; $B = 46.0     # margins; R leaves room for the legend
$PW = $W - $L - $R
$PH = $H - $T - $B

$StepMinutes = 6
$Samples = [int](24 * 60 / $StepMinutes)

function Get-XCoordinate { param([double]$Hour)    return $L + ($Hour / 24.0) * $PW }
function Get-YCoordinate { param([double]$Percent) return $T + (1.0 - ($Percent / 100.0)) * $PH }

# ---------------------------------------------------------------------------
# the curves, straight from the model
# ---------------------------------------------------------------------------
$series = @(
    @{ Kt = 0.95; Label = 'clear sky';      Sub = 'Kt 0.95'; Colour = '#f0a500' }
    @{ Kt = 0.50; Label = 'broken cloud';   Sub = 'Kt 0.50'; Colour = '#4c9be8' }
    @{ Kt = 0.15; Label = 'heavy overcast'; Sub = 'Kt 0.15'; Colour = '#a371f7' }
)

$nightSpans = New-Object System.Collections.ArrayList
$inNight = $false; $spanStart = 0.0

foreach ($s in $series) { $s.Points = New-Object System.Collections.ArrayList }

foreach ($i in 0..$Samples) {
    $hour = $i * $StepMinutes / 60.0
    $when = $Date.Date.AddMinutes($i * $StepMinutes)
    $alt  = Get-SunAltitude -Lat $Latitude -Lon $Longitude -When $when

    # night band: below the ramp the sun term is pinned at the night level
    $isNight = ($alt -lt -12.0)
    if ($isNight -and -not $inNight)      { $inNight = $true;  $spanStart = $hour }
    elseif (-not $isNight -and $inNight)  { $inNight = $false; [void]$nightSpans.Add(@($spanStart, $hour)) }

    foreach ($s in $series) {
        $m = Get-TargetBrightness -SunAltitudeDeg $alt -Kt $s.Kt
        [void]$s.Points.Add(@((Get-XCoordinate $hour), (Get-YCoordinate $m.Target)))
    }
}
if ($inNight) { [void]$nightSpans.Add(@($spanStart, 24.0)) }

# ---------------------------------------------------------------------------
# svg
# ---------------------------------------------------------------------------
$muted = '#8b949e'      # legible on GitHub's light and dark themes alike
$grid  = '#8b949e'

$sb = New-Object System.Text.StringBuilder
function Add-Line { param([string]$S) [void]$sb.AppendLine($S) }

Add-Line ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {0} {1}" width="{0}" height="{1}" font-family="ui-sans-serif,-apple-system,Segoe UI,Helvetica,Arial,sans-serif">' -f $W, $H)
Add-Line '  <title>Monitor brightness across one day, by sky condition</title>'
Add-Line ('  <desc>Generated by Tools/New-CurveChart.ps1 from BrightnessCore.ps1 at {0:N1} deg N on {1:yyyy-MM-dd}.</desc>' -f $Latitude, $Date)

# night bands
foreach ($span in $nightSpans) {
    $x1 = Get-XCoordinate $span[0]; $x2 = Get-XCoordinate $span[1]
    Add-Line ('  <rect x="{0:N1}" y="{1:N1}" width="{2:N1}" height="{3:N1}" fill="{4}" opacity="0.10"/>' -f `
              $x1, $T, ($x2 - $x1), $PH, $grid)
}

# horizontal gridlines + y labels
foreach ($pct in 0, 25, 50, 75, 100) {
    $y = Get-YCoordinate $pct
    Add-Line ('  <line x1="{0:N1}" y1="{1:N1}" x2="{2:N1}" y2="{1:N1}" stroke="{3}" stroke-opacity="0.22" stroke-width="1"/>' -f `
              $L, $y, ($L + $PW), $grid)
    Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="12" text-anchor="end" dominant-baseline="middle">{3}%</text>' -f `
              ($L - 10), $y, $muted, $pct)
}

# x labels
foreach ($hour in 0, 3, 6, 9, 12, 15, 18, 21, 24) {
    $x = Get-XCoordinate $hour
    Add-Line ('  <line x1="{0:N1}" y1="{1:N1}" x2="{0:N1}" y2="{2:N1}" stroke="{3}" stroke-opacity="0.22" stroke-width="1"/>' -f `
              $x, $T, ($T + $PH), $grid)
    Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="12" text-anchor="middle">{3:00}:00</text>' -f `
              $x, ($T + $PH + 20), $muted, $hour)
}

# the curves
foreach ($s in $series) {
    $d = ($s.Points | ForEach-Object { '{0:N1},{1:N1}' -f $_[0], $_[1] }) -join ' L'
    Add-Line ('  <path d="M{0}" fill="none" stroke="{1}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>' -f `
              $d, $s.Colour)
}

# legend
$ly = $T + 6
foreach ($s in $series) {
    $lx = $L + $PW + 22
    Add-Line ('  <line x1="{0:N1}" y1="{1:N1}" x2="{2:N1}" y2="{1:N1}" stroke="{3}" stroke-width="3" stroke-linecap="round"/>' -f `
              $lx, $ly, ($lx + 22), $s.Colour)
    Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="13" dominant-baseline="middle">{3}</text>' -f `
              ($lx + 30), $ly, $muted, $s.Label)
    Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="11" opacity="0.75">{3}</text>' -f `
              ($lx + 30), ($ly + 15), $muted, $s.Sub)
    $ly += 42
}
Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="11" opacity="0.7">shaded = sun</text>' -f `
          ($L + $PW + 22), ($ly + 4), $muted)
Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="11" opacity="0.7">below -12 deg</text>' -f `
          ($L + $PW + 22), ($ly + 18), $muted)

# axis titles
Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="12" opacity="0.8">brightness</text>' -f `
          $L, ($T - 12), $muted)
Add-Line ('  <text x="{0:N1}" y="{1:N1}" fill="{2}" font-size="11" text-anchor="end" opacity="0.7">{3:N0} deg N, equinox</text>' -f `
          ($L + $PW), ($T - 12), $muted, $Latitude)

Add-Line '</svg>'

$dir = Split-Path $OutPath -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Host "Wrote $OutPath" -ForegroundColor Green
